when:
  - event: release

skip_clone: true

labels:
  zone: CLOUD

steps:
  - name: Ansible playbook
    image: itkdev/ansible-plugin:1
    pull: true
    settings:
      id:
        from_secret: id
      secret:
        from_secret: secret
      host:
        from_secret: prod_host
      path:
        from_secret: prod_path
      user:
        from_secret: user
      playbook: 'release'
      pre_up:
        # Fixes issue with 'Drupal\mysql\Driver\Database\mysql\Connection' not found
        - itkdev-docker-compose-server run --rm phpfpm composer dump-autoload
        - itkdev-docker-compose-server run --rm phpfpm vendor/bin/drush --yes cache:rebuild
        - itkdev-docker-compose-server run --rm phpfpm vendor/bin/drush --yes deploy
      cron:
        cron:
          minute: '*/5'
          hour: '*'
          day: '*'
          month: '*'
          weekday: '*'
          job: 'itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes core:cron'
#        whisper:
#          minute: '0'
#          hour: '3'
#          day: '*'
#          month: '*'
#          weekday: '*'
#          job: 'itkdev-docker-compose-server exec phpfpm vendor/bin/drush --yes giv-din-stemme:qualify:all'
